/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: dlinfer.i

package dlinfer

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
extern void _wrap_Swig_free_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern uintptr_t _wrap_new_StringVector__SWIG_0_dlinfer_e2685c33728dd3a3(void);
extern uintptr_t _wrap_new_StringVector__SWIG_1_dlinfer_e2685c33728dd3a3(swig_type_1 arg1);
extern swig_type_2 _wrap_StringVector_size_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern swig_type_3 _wrap_StringVector_capacity_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_StringVector_reserve_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_StringVector_isEmpty_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_StringVector_clear_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_StringVector_add_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_type_5 arg2);
extern swig_type_6 _wrap_StringVector_get_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_StringVector_set_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_intgo arg2, swig_type_7 arg3);
extern void _wrap_delete_StringVector_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern uintptr_t _wrap_new_ByteVector__SWIG_0_dlinfer_e2685c33728dd3a3(void);
extern uintptr_t _wrap_new_ByteVector__SWIG_1_dlinfer_e2685c33728dd3a3(swig_type_8 arg1);
extern swig_type_9 _wrap_ByteVector_size_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern swig_type_10 _wrap_ByteVector_capacity_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_ByteVector_reserve_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_type_11 arg2);
extern _Bool _wrap_ByteVector_isEmpty_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_ByteVector_clear_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_ByteVector_add_dlinfer_e2685c33728dd3a3(uintptr_t arg1, char arg2);
extern char _wrap_ByteVector_get_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_ByteVector_set_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_intgo arg2, char arg3);
extern void _wrap_delete_ByteVector_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern uintptr_t _wrap_new_InferenceEngineConfigurator__SWIG_0_dlinfer_e2685c33728dd3a3(swig_type_12 arg1, uintptr_t arg2, swig_type_13 arg3, swig_type_14 arg4);
extern uintptr_t _wrap_new_InferenceEngineConfigurator__SWIG_1_dlinfer_e2685c33728dd3a3(swig_type_15 arg1, uintptr_t arg2, swig_type_16 arg3);
extern void _wrap_InferenceEngineConfigurator_loadImages__SWIG_0_dlinfer_e2685c33728dd3a3(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_InferenceEngineConfigurator_loadImages__SWIG_1_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_type_17 arg2);
extern void _wrap_InferenceEngineConfigurator_infer_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern uintptr_t _wrap_InferenceEngineConfigurator_getTopResult_dlinfer_e2685c33728dd3a3(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_InferenceEngineConfigurator_printGetPerformanceCounts_dlinfer_e2685c33728dd3a3(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_InferenceEngineConfigurator_setISLVC2012MeanScalars_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_InferenceEngineConfigurator_loadModel_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
extern void _wrap_delete_InferenceEngineConfigurator_dlinfer_e2685c33728dd3a3(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

type SwigcptrStringVector uintptr

func (p SwigcptrStringVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringVector) SwigIsStringVector() {
}

func NewStringVector__SWIG_0() (_swig_ret StringVector) {
	var swig_r StringVector
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_new_StringVector__SWIG_0_dlinfer_e2685c33728dd3a3()))
	return swig_r
}

func NewStringVector__SWIG_1(arg1 int64) (_swig_ret StringVector) {
	var swig_r StringVector
	_swig_i_0 := arg1
	swig_r = (StringVector)(SwigcptrStringVector(C._wrap_new_StringVector__SWIG_1_dlinfer_e2685c33728dd3a3(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewStringVector(a ...interface{}) StringVector {
	argc := len(a)
	if argc == 0 {
		return NewStringVector__SWIG_0()
	}
	if argc == 1 {
		return NewStringVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrStringVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVector_size_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_StringVector_capacity_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVector_reserve_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrStringVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_StringVector_isEmpty_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrStringVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_StringVector_clear_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrStringVector) Add(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StringVector_add_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrStringVector) Get(arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r_p := C._wrap_StringVector_get_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func (arg1 SwigcptrStringVector) Set(arg2 int, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_StringVector_set_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func DeleteStringVector(arg1 StringVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_StringVector_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

type StringVector interface {
	Swigcptr() uintptr
	SwigIsStringVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 string)
	Get(arg2 int) (_swig_ret string)
	Set(arg2 int, arg3 string)
}

type SwigcptrByteVector uintptr

func (p SwigcptrByteVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrByteVector) SwigIsByteVector() {
}

func NewByteVector__SWIG_0() (_swig_ret ByteVector) {
	var swig_r ByteVector
	swig_r = (ByteVector)(SwigcptrByteVector(C._wrap_new_ByteVector__SWIG_0_dlinfer_e2685c33728dd3a3()))
	return swig_r
}

func NewByteVector__SWIG_1(arg1 int64) (_swig_ret ByteVector) {
	var swig_r ByteVector
	_swig_i_0 := arg1
	swig_r = (ByteVector)(SwigcptrByteVector(C._wrap_new_ByteVector__SWIG_1_dlinfer_e2685c33728dd3a3(C.swig_type_8(_swig_i_0))))
	return swig_r
}

func NewByteVector(a ...interface{}) ByteVector {
	argc := len(a)
	if argc == 0 {
		return NewByteVector__SWIG_0()
	}
	if argc == 1 {
		return NewByteVector__SWIG_1(a[0].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrByteVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ByteVector_size_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ByteVector_capacity_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ByteVector_reserve_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_type_11(_swig_i_1))
}

func (arg1 SwigcptrByteVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ByteVector_isEmpty_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_ByteVector_clear_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrByteVector) Add(arg2 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ByteVector_add_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.char(_swig_i_1))
}

func (arg1 SwigcptrByteVector) Get(arg2 int) (_swig_ret byte) {
	var swig_r byte
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (byte)(C._wrap_ByteVector_get_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrByteVector) Set(arg2 int, arg3 byte) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_ByteVector_set_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.char(_swig_i_2))
}

func DeleteByteVector(arg1 ByteVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_ByteVector_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

type ByteVector interface {
	Swigcptr() uintptr
	SwigIsByteVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 byte)
	Get(arg2 int) (_swig_ret byte)
	Set(arg2 int, arg3 byte)
}

type SwigcptrInferenceEngineConfigurator uintptr

func (p SwigcptrInferenceEngineConfigurator) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrInferenceEngineConfigurator) SwigIsInferenceEngineConfigurator() {
}

func NewInferenceEngineConfigurator__SWIG_0(arg1 string, arg2 StringVector, arg3 string, arg4 string) (_swig_ret InferenceEngineConfigurator) {
	var swig_r InferenceEngineConfigurator
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (InferenceEngineConfigurator)(SwigcptrInferenceEngineConfigurator(C._wrap_new_InferenceEngineConfigurator__SWIG_0_dlinfer_e2685c33728dd3a3(*(*C.swig_type_12)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_14)(unsafe.Pointer(&_swig_i_3)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func NewInferenceEngineConfigurator__SWIG_1(arg1 string, arg2 StringVector, arg3 string) (_swig_ret InferenceEngineConfigurator) {
	var swig_r InferenceEngineConfigurator
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (InferenceEngineConfigurator)(SwigcptrInferenceEngineConfigurator(C._wrap_new_InferenceEngineConfigurator__SWIG_1_dlinfer_e2685c33728dd3a3(*(*C.swig_type_15)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1), *(*C.swig_type_16)(unsafe.Pointer(&_swig_i_2)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func NewInferenceEngineConfigurator(a ...interface{}) InferenceEngineConfigurator {
	argc := len(a)
	if argc == 3 {
		return NewInferenceEngineConfigurator__SWIG_1(a[0].(string), a[1].(StringVector), a[2].(string))
	}
	if argc == 4 {
		return NewInferenceEngineConfigurator__SWIG_0(a[0].(string), a[1].(StringVector), a[2].(string), a[3].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrInferenceEngineConfigurator) LoadImages__SWIG_0(arg2 StringVector) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_InferenceEngineConfigurator_loadImages__SWIG_0_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrInferenceEngineConfigurator) LoadImages__SWIG_1(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_InferenceEngineConfigurator_loadImages__SWIG_1_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (p SwigcptrInferenceEngineConfigurator) LoadImages(a ...interface{}) {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(SwigcptrStringVector); !ok {
			goto check_1
		}
		p.LoadImages__SWIG_0(a[0].(StringVector))
		return
	}
check_1:
	if argc == 1 {
		p.LoadImages__SWIG_1(a[0].(string))
		return
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrInferenceEngineConfigurator) Infer() {
	_swig_i_0 := arg1
	C._wrap_InferenceEngineConfigurator_infer_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrInferenceEngineConfigurator) GetTopResult(arg2 uint) (_swig_ret Std_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_) {
	var swig_r Std_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Std_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_)(SwigcptrStd_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_(C._wrap_InferenceEngineConfigurator_getTopResult_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrInferenceEngineConfigurator) PrintGetPerformanceCounts(arg2 Std_ostream) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_InferenceEngineConfigurator_printGetPerformanceCounts_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrInferenceEngineConfigurator) SetISLVC2012MeanScalars() {
	_swig_i_0 := arg1
	C._wrap_InferenceEngineConfigurator_setISLVC2012MeanScalars_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrInferenceEngineConfigurator) LoadModel() {
	_swig_i_0 := arg1
	C._wrap_InferenceEngineConfigurator_loadModel_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

func DeleteInferenceEngineConfigurator(arg1 InferenceEngineConfigurator) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_InferenceEngineConfigurator_dlinfer_e2685c33728dd3a3(C.uintptr_t(_swig_i_0))
}

type InferenceEngineConfigurator interface {
	Swigcptr() uintptr
	SwigIsInferenceEngineConfigurator()
	LoadImages(a ...interface{})
	Infer()
	GetTopResult(arg2 uint) (_swig_ret Std_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_)
	PrintGetPerformanceCounts(arg2 Std_ostream)
	SetISLVC2012MeanScalars()
	LoadModel()
}

type SwigcptrStd_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_ uintptr
type Std_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_ interface {
	Swigcptr() uintptr
}

func (p SwigcptrStd_vector_Sl_InferenceEngineConfigurator_InferenceResults_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_ostream uintptr
type Std_ostream interface {
	Swigcptr() uintptr
}

func (p SwigcptrStd_ostream) Swigcptr() uintptr {
	return uintptr(p)
}
